### ISSUE TITLE
Heroku setup/Push

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#1]
Need to be able to push project to Heroku for hosting. Simple setup needed

**Comment by Gondee** [comment]
Add post greSQL studio plugin to heroku

**Comment by Gondee** [comment]
Heroku repo created. Need to add you guys on. 
Request Postgre plugin added as well. 

What is everyone's Heroku Emails?

**Comment by scojasp** [comment]
scojasp@gmail.com, adding would be very helpful

**Comment by Gondee** [comment]
Added

**Comment by lef592** [comment]
Added the gemfile stuff from Chapter 1 of the tutorial that is needed for Heroku. It sounds like you already set up something for it.

**Comment by lef592** [comment]
Is this issue closed if the Heroku is already set up, or what else does it need?

**Comment by scojasp** [comment]
Successful push to Heroku, however cannot make any user accounts. Receive error:
<code>app/controllers/users_controller.rb:34:in 'create'
2015-11-03T22:15:20.265444+00:00 app[web.1]: ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
2015-11-03T22:15:20.265451+00:00 app[web.1]:   app/mailers/user_mailer.rb:10:in `account_activation'</code>
Other than this, Heroku appears to be working correctly.

To view debug logs from Heroku in Cloud9: <code>heroku logs --app scdp</code> after initial heroku setup (<code>heroku login</code>).

If the sole purpose of this issue was to get a displayable version of the site onto Heroku, then I believe this issue can be closed. Else, if the purpose of this issue is to make Heroku's version feature-complete, this issue should stay open.

However, in the latter case, it may be better to close this, and create separate additional issues.

**Comment by scojasp** [comment]
PG database fixed.
