### ISSUE TITLE
Change name to: About Us

### ISSUE THREAD

**Issue by maroon15** [Gondee/SocialCurveManager#107]
Social Curve is an easy to use platform for sharing monetized content. Content is provided by our hand selected publishing partners who lead the internet with high quality content. Influential social stars use our platform to browse this great content to share with their fans. 

We create highly engaged audiences that earn influencers the best income.

**Comment by Gondee** [comment]
You want to replace: "Social Curve was fashioned to positively leverage influential social media, expand the delivery of high quality content from top publishers, and engage followings in a new and innovative way. As the online social sphere progresses, we are continually identifying strategic areas where influential social stars can monetize their thriving community of fans, while continuing to promote the foundational interactions fans know and love. Our unique and intuitive methodology pairs content from great publishers seamlessly with social groups that have been identified as the optimal recipients. As more data becomes available, Social Curve continues to tweak content distribution so that publishers have the leanest possible channel, while audiences are presented with personally appealing content based on their interests. To learn more, scroll down to see where you can fit into our vision."??

**Comment by maroon15** [comment]
Yea, we need to keep it simple

**Comment by Gondee** [comment]
Its a bit sparse on the page but ight
