### ISSUE TITLE
Connect Flatty Bootstrap Theme

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#2]
Need to connect the Flatty theme to the project for future UX features. Flatty uses compass and SASS, which provide some challenges. I spent some time attempting to get it connected, and compass threw compiler errors. Further debug needed.

**Comment by scojasp** [comment]
Is this the same Flatty theme as in our Dropbox folders?

**Comment by Gondee** [comment]
Yes, under the products folder.

**Comment by lef592** [comment]
Well, tried doing this but also ran into problems. Using the instructions under "Ruby on Rails" on this page: http://www.bublinastudio.com/flattybs3/docs/get_started.html I was able to install what it asked me to. However, this pretty much broke everything because cloud9 tried to get stuff it shouldn't out of the flatty stuff.

**Comment by Gondee** [comment]
Were you running into compass compile errors? I spent some time with this as well, and I'm curious if we landed in the same spot.

**Comment by lef592** [comment]
I don't think they were compile errors exactly. It was more like it compiled just fine, but when I booted up the website and tried to say, visit the login page, it crashed and got that red error screen. This seemed to happen because it was trying to get there by using stuff in flatty, rather than what it should have used.

**Comment by scojasp** [comment]
Well, it's 4:16 am, and Flatty now completely works with our site. Just need to style it the way we want it, then this can be checked off.

For a barebones working implementation, check out branch <code>ud_flatty</code>.
To contribute to the implementation I am currently working on, check out branch <code>flatty_integration</code>.
Any contributions you can make to my <code>flatty_integration</code> code would be amazing.

Ignore anything that is prefixed/suffixed with OLD - those are files I'm trying to use to get everything working on Flatty, based on the old stuff.

I have an 8am too. Joy. Guess I'm sleeping through that. :stuck_out_tongue_closed_eyes:
Enjoy the working theme!

**Comment by scojasp** [comment]
As a side note, if you are having trouble when running <code>bundle install</code>, delete your Gemfile.<b>lock</b> and rerun.

**Comment by Gondee** [comment]
Wow! Your on fire ahah! Great work! 
Would you mind showing me how you got it working later?

**Comment by Gondee** [comment]
![Mind Blown](http://i0.kym-cdn.com/entries/icons/original/000/009/993/tumblr_m0wb2xz9Yh1r08e3p.jpg)

**Comment by scojasp** [comment]
Sure thing! It was a bit obtuse, I will admit.

**Comment by Gondee** [comment]
Closing this issue
