### ISSUE TITLE
Google Link Shortener 

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#4]
Need to add a Gem capable of managing links from google link shortener. There is some Gems available, so once we get the KEY from google, we should be able to integrate this fairly easily.

**Comment by scojasp** [comment]
Being that this will be for a project that is intended to generate profit, the best Gems to use will be the official API Gems, rather than someone else's Gems.

Google's own API client is <code>google-api-client</code>:
https://developers.google.com/api-client-library/ruby/apis/urlshortener/v1?hl=en
<code>gem install google-api-client</code>

This is currently in Alpha, but this beats having to worry about if other developers using the CC license will go after you.

**Comment by Gondee** [comment]
100% agree, ill do some research and see if the install base has had any issues. I know there are some solid OC ones out there, even ones in the ruby install path, but your right, first party is preferred.

**Comment by Gondee** [comment]
Ok, Google API checks out. I'm going to get to work on this now. Here is the reference material I will be using. 
https://developers.google.com/url-shortener/v1/getting_started

Edit: We are using Ruby 1.9.3 I believe, which is not supported by the official plugin. I will upgrade to the latest stable ruby in the LinkShortener Branch

**Comment by Gondee** [comment]
Installed on Gem Branch, Reference information here: https://github.com/joshnesbitt/google_url_shortener
