### ISSUE TITLE
Edit Lorem Ipsum on /users/edit and /users/show

### ISSUE THREAD

**Issue by scojasp** [Gondee/SocialCurveManager#78]

**Comment by lef592** [comment]
Ok. Added. Here is the descriptions so you don't have to look for them. I made them general since the same descriptions are seen by both user and publisher. 

User Edit: (AKA Settings) 

This is the information you use to sign in, including the email linked to your account and your password. If this information needs to be updated, you can do so here. If you feel the security of your account has been compromised, it may be a good idea to change your password. 

This is the information that Social Curve uses to contact you, including your name, address, phone number, and URL. If any of this information is outdated or incorrect, it may be a good idea to update or correct it. Otherwise, we may be unable to contact you.

User Show: (AKA Profile) 

This is your sign in information. For security reasons, only your email is displayed here. If you have forgotten or otherwise lost your password, please click the edit button down below. You will be redirected to a page were you can update your password as well as your email if need be.

This is your contact information. Your name, address, phone number, and URL are displayed here. If you find that any of this information is incorrect or outdated, please click the edit button down below and update this information. It is important that this information remains accurate and correct so that we may contact you.
